import 'package:my_flutter_app/models/news_article.dart';

// Ported from FE: News.jsx — static news data
const _goldImg = 'https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=1200&q=80';
const _silverImg = 'https://images.unsplash.com/photo-1610375461369-d613b5647341?auto=format&fit=crop&w=1200&q=80';
const _exRateImg = 'https://images.unsplash.com/photo-1554224154-26032fced8bd?auto=format&fit=crop&w=1200&q=80';
const _oilImg = 'https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=1200&q=80';

const List<String> newsCategories = ['All', 'Gold', 'Silver', 'Exchange Rate', 'Oil'];

const List<NewsArticle> newsData = [
  // --- GOLD ---
  NewsArticle(id: 1, title: 'Gold slips and heads for second consecutive weekly fall', category: 'Gold', source: 'Reuters', author: 'Ashitha Shivaprasad', date: '2026-03-13', readTime: '3 min read', image: _goldImg, summary: 'Gold eased as the dollar stayed firm and rate-cut expectations softened amid oil-driven inflation worries.', link: 'https://www.reuters.com/world/india/gold-set-weekly-drop-oil-price-surge-weighs-rate-cut-hopes-2026-03-13/'),
  NewsArticle(id: 2, title: 'Gold slips over 1% on strong dollar, easing rate-cut bets', category: 'Gold', source: 'Reuters', author: 'Ashitha Shivaprasad', date: '2026-03-12', readTime: '3 min read', image: _goldImg, summary: 'A stronger U.S. dollar and persistent inflation concerns pulled bullion lower in a volatile session.', link: 'https://www.reuters.com/world/india/gold-steady-dipbuying-offsets-firm-dollar-us-inflation-woes-2026-03-12/'),
  NewsArticle(id: 3, title: 'Gold eases as firmer dollar, lingering inflation concerns persist', category: 'Gold', source: 'Reuters', author: 'Ashitha Shivaprasad', date: '2026-03-11', readTime: '3 min read', image: _goldImg, summary: 'Bullion stayed under pressure as investors weighed inflation jitters and the path of U.S. rates.', link: 'https://www.reuters.com/world/india/gold-edges-higher-inflation-jitters-ease-key-us-data-focus-2026-03-11/'),
  NewsArticle(id: 4, title: 'Gold slips on stronger dollar, higher rate expectations', category: 'Gold', source: 'Reuters', author: 'Reuters Staff', date: '2026-03-09', readTime: '3 min read', image: _goldImg, summary: 'Oil-linked inflation concerns helped strengthen the dollar and weighed on gold demand.', link: 'https://www.reuters.com/world/india/gold-prices-fall-firmer-dollar-dimming-rate-cut-hopes-2026-03-09/'),
  NewsArticle(id: 5, title: 'Gold slips, silver down nearly 14% on firmer dollar', category: 'Gold', source: 'Reuters', author: 'Reuters Staff', date: '2026-02-05', readTime: '4 min read', image: _goldImg, summary: 'A broad sell-off in precious metals hit both gold and silver as the dollar gained ground.', link: 'https://www.reuters.com/world/india/gold-rises-over-1-geopolitical-economic-tensions-lift-precious-metals-2026-02-05/'),
  NewsArticle(id: 6, title: 'Gold set for biggest daily gain since 2008, silver also rebounds', category: 'Gold', source: 'Reuters', author: 'Reuters Staff', date: '2026-02-03', readTime: '4 min read', image: _goldImg, summary: 'Bargain hunters stepped back into bullion after a sharp two-day washout in the market.', link: 'https://www.reuters.com/world/india/gold-rebounds-more-than-3-after-sharp-selloff-2026-02-03/'),
  NewsArticle(id: 7, title: 'Gold tops \$4,900/oz; silver and platinum extend record rally', category: 'Gold', source: 'Reuters', author: 'Reuters Staff', date: '2026-01-22', readTime: '4 min read', image: _goldImg, summary: 'Safe-haven demand and a softer dollar helped gold break to a fresh record above \$4,900.', link: 'https://www.reuters.com/world/india/gold-falls-easing-geopolitical-tensions-dampen-safe-haven-demand-2026-01-22/'),
  NewsArticle(id: 8, title: 'Gold cracks \$4,600/oz as Fed uncertainty fans safe-haven demand', category: 'Gold', source: 'Reuters', author: 'Reuters Staff', date: '2026-01-12', readTime: '3 min read', image: _goldImg, summary: 'Investors turned to bullion as policy uncertainty around the Fed boosted defensive positioning.', link: 'https://www.reuters.com/world/india/gold-silver-notch-record-highs-safe-haven-demand-fed-rate-cut-bets-2026-01-12/'),
  NewsArticle(id: 9, title: 'Precious metals rise early in 2026 on rate-cut bets and safe-haven demand', category: 'Gold', source: 'Reuters', author: 'Reuters Staff', date: '2026-01-02', readTime: '3 min read', image: _goldImg, summary: 'Gold started the year firm while silver and platinum outperformed on supply and policy themes.', link: 'https://www.reuters.com/world/india/precious-metals-kick-off-new-year-higher-after-robust-2025-rally-2026-01-02/'),
  NewsArticle(id: 10, title: 'Gold rebounds, poised to cap off best year in over four decades', category: 'Gold', source: 'Reuters', author: 'Reuters Staff', date: '2025-12-30', readTime: '4 min read', image: _goldImg, summary: 'Bullion steadied near year-end after a record-setting year for precious metals.', link: 'https://www.reuters.com/world/india/gold-bounces-back-two-week-low-silver-recovers-2025-12-30/'),

  // --- SILVER ---
  NewsArticle(id: 11, title: 'Silver and gold prices cool in Vietnam\'s domestic market', category: 'Silver', source: 'Investing.com Vietnam', author: 'Kieu Giang', date: '2026-03-13', readTime: '3 min read', image: _silverImg, summary: 'Domestic bullion and silver prices eased as the global precious-metals complex corrected.', link: 'https://vn.investing.com/news/commodities-news/gia-vang-bac-trong-nuoc-dong-loat-ha-nhiet-2561966'),
  NewsArticle(id: 12, title: 'Silver slips with gold as firmer dollar pressure returns', category: 'Silver', source: 'Reuters', author: 'Ashitha Shivaprasad', date: '2026-03-12', readTime: '3 min read', image: _silverImg, summary: 'Silver also softened as Treasury yields rose and the dollar stayed elevated.', link: 'https://www.reuters.com/world/india/gold-steady-dipbuying-offsets-firm-dollar-us-inflation-woes-2026-03-12/'),
  NewsArticle(id: 13, title: 'UBS says silver upside may be limited over the next 12 months', category: 'Silver', source: 'Investing.com Vietnam', author: 'Investing.com', date: '2026-03-05', readTime: '4 min read', image: _silverImg, summary: 'The bank kept a constructive but more measured view after silver\'s explosive run-up.', link: 'https://vn.investing.com/news/commodities-news/ubs-du-bao-gia-bac-co-tiem-nang-tang-han-che-trong-12-thang-toi-2554868'),
  NewsArticle(id: 14, title: 'Speculative frenzy catapults silver above \$100 an ounce', category: 'Silver', source: 'Reuters', author: 'Reuters Staff', date: '2026-01-23', readTime: '5 min read', image: _silverImg, summary: 'Retail buying, ETF inflows and supply tightness drove an extraordinary move in silver.', link: 'https://www.reuters.com/world/india/gold-silver-platinum-extend-recordsetting-rally-2026-01-23/'),
  NewsArticle(id: 15, title: 'Silver powers to a fresh record high with gold and platinum', category: 'Silver', source: 'Reuters', author: 'Reuters Staff', date: '2026-01-12', readTime: '3 min read', image: _silverImg, summary: 'Silver extended its breakout as safe-haven flows spread across the precious metals complex.', link: 'https://www.reuters.com/world/india/gold-silver-notch-record-highs-safe-haven-demand-fed-rate-cut-bets-2026-01-12/'),
  NewsArticle(id: 16, title: 'Silver rises 9% to hit a fresh record high', category: 'Silver', source: 'Reuters', author: 'Reuters Staff', date: '2025-12-26', readTime: '3 min read', image: _silverImg, summary: 'A sharp year-end burst pushed silver to another all-time high on strong momentum.', link: 'https://www.reuters.com/world/india/silver-rises-9-hit-fresh-record-high-2025-12-26/'),
  NewsArticle(id: 17, title: 'Silver gains after Fed rate cut while gold also rebounds', category: 'Silver', source: 'Reuters', author: 'Reuters Staff', date: '2025-12-10', readTime: '4 min read', image: _silverImg, summary: 'Silver continued to outperform as the Fed decision reinforced precious-metals momentum.', link: 'https://www.reuters.com/world/india/gold-inches-up-ahead-fed-verdict-silver-powers-fresh-records-above-60-2025-12-10/'),

  // --- EXCHANGE RATE ---
  NewsArticle(id: 18, title: 'USD exchange rate today: Dollar index rises for the third straight session', category: 'Exchange Rate', source: 'Vietnam.vn', author: 'Bao Cong Thuong', date: '2026-03-13', readTime: '2 min read', image: _exRateImg, summary: 'The State Bank\'s reference rate and the broader dollar trend remained key talking points in Vietnam.', link: 'https://www.vietnam.vn/en/ty-gia-usd-hom-nay-13-3-2026-dollar-index-tang-phien-thu-ba-lien-tiep'),
  NewsArticle(id: 19, title: 'Commercial banks slightly increased the USD exchange rate', category: 'Exchange Rate', source: 'Vietnam.vn', author: 'Vietnam.vn', date: '2026-03-13', readTime: '2 min read', image: _exRateImg, summary: 'Bank quotes edged up as domestic traders tracked movements in the global U.S. dollar.', link: 'https://www.vietnam.vn/en/ngan-hang-thuong-mai-tang-nhe-ty-gia-usd'),
  NewsArticle(id: 20, title: 'Dollar rises broadly as investors weigh Middle East risks', category: 'Exchange Rate', source: 'Reuters', author: 'Saqib Iqbal Ahmed', date: '2026-03-13', readTime: '4 min read', image: _exRateImg, summary: 'The greenback benefited from safe-haven demand as markets priced in geopolitical stress.', link: 'https://www.reuters.com/world/asia-pacific/dollar-poised-second-weekly-gain-with-no-end-sight-iran-war-2026-03-13/'),
  NewsArticle(id: 21, title: 'Dollar flirts with new 2026 highs as oil jump hurts euro', category: 'Exchange Rate', source: 'Reuters', author: 'Saqib Iqbal Ahmed', date: '2026-03-12', readTime: '3 min read', image: _exRateImg, summary: 'A stronger dollar became an important benchmark for comparing global asset prices.', link: 'https://www.reuters.com/world/asia-pacific/us-dollar-hovers-near-2026-highs-oils-rise-spurs-hawkish-central-bank-bets-2026-03-12/'),
  NewsArticle(id: 22, title: 'US dollar surges above 27,000 VND on the free market', category: 'Exchange Rate', source: 'Vietnam.vn', author: 'Vietnam.vn', date: '2026-03-10', readTime: '2 min read', image: _exRateImg, summary: 'Parallel-market pricing highlighted why currency conversion matters in local-vs-global comparisons.', link: 'https://www.vietnam.vn/en/gia-usd-tang-kich-tran-thi-truong-tu-do-vuot-27-000-dong-usd'),

  // --- OIL ---
  NewsArticle(id: 23, title: 'US says oil from strategic reserve to start reaching market next week', category: 'Oil', source: 'Reuters', author: 'Reuters', date: '2026-03-14', readTime: '3 min read', image: _oilImg, summary: 'Washington moved to cool the market by releasing oil from the strategic reserve.', link: 'https://www.reuters.com/business/energy/us-says-oil-strategic-reserve-start-reaching-market-next-week-2026-03-14/'),
  NewsArticle(id: 24, title: 'Goldman hikes average Brent oil forecast to over \$100 for March', category: 'Oil', source: 'Reuters', author: 'Reuters', date: '2026-03-13', readTime: '4 min read', image: _oilImg, summary: 'Escalating Middle East disruptions forced a major upward revision to near-term oil forecasts.', link: 'https://www.reuters.com/business/energy/goldman-hikes-average-brent-oil-forecast-over-100-barrel-march-2026-03-13/'),
  NewsArticle(id: 25, title: 'Iran war: Oil markets brace for wild price swings', category: 'Oil', source: 'Reuters', author: 'Reuters', date: '2026-03-13', readTime: '4 min read', image: _oilImg, summary: 'The market prepared for rapid repricing as conflict threatened one of the world\'s key chokepoints.', link: 'https://www.reuters.com/markets/commodities/energy/iran-war-oil-markets-brace-wild-price-swings-2026-03-13/'),
  NewsArticle(id: 26, title: 'Oil dives and settles down 11% after Trump predicts de-escalation', category: 'Oil', source: 'Reuters', author: 'Reuters', date: '2026-03-10', readTime: '3 min read', image: _oilImg, summary: 'One of the biggest one-day drops in years showed how sensitive oil remains to geopolitical headlines.', link: 'https://www.reuters.com/business/energy/oil-falls-over-6-trump-predicts-middle-east-de-escalation-2026-03-10/'),
  NewsArticle(id: 27, title: 'Kharg Island — a key hub for Iran oil exports', category: 'Oil', source: 'Reuters', author: 'Reuters', date: '2026-03-14', readTime: '3 min read', image: _oilImg, summary: 'The report explains why infrastructure around Kharg matters so much for global supply risk.', link: 'https://www.reuters.com/business/energy/kharg-island-struck-by-us-is-key-hub-iran-oil-exports-2026-03-14/'),
];
